# Generated by Django 5.2.14 on 2026-07-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
