# Generated by Django 5.2.14 on 2026-07-21 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=10)),
                ('reference_id', models.CharField(blank=True, help_text='Student ID from MySQL or Teacher ID from PostgreSQL.', max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ums_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'reference_id', 'user__username'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('role', 'reference_id'), name='unique_role_reference_account')],
            },
        ),
    ]
