# Generated by Django 5.2.14 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusCardApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_ref", models.CharField(max_length=30)),
                ("student_name", models.CharField(max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("semester", models.PositiveSmallIntegerField(default=1)),
                ("academic_year", models.CharField(default="2026-2027", max_length=9)),
                ("phone", models.CharField(max_length=20)),
                ("pickup_point", models.CharField(max_length=150)),
                ("address", models.TextField()),
                ("emergency_contact", models.CharField(max_length=20)),
                ("blood_group", models.CharField(blank=True, choices=[("", "Select blood group"), ("A+", "A+"), ("A-", "A-"), ("B+", "B+"), ("B-", "B-"), ("AB+", "AB+"), ("AB-", "AB-"), ("O+", "O+"), ("O-", "O-")], max_length=3)),
                ("status", models.CharField(choices=[("Pending", "Pending Review"), ("Approved", "Approved"), ("Rejected", "Rejected"), ("Printed", "Card Printed"), ("Collected", "Collected")], default="Pending", max_length=12)),
                ("card_number", models.CharField(blank=True, max_length=30)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
            ],
            options={"ordering": ["status", "-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="buscardapplication",
            constraint=models.UniqueConstraint(fields=("student_ref", "academic_year"), name="unique_bus_card_application_per_year"),
        ),
    ]
