# Generated by Django 5.2.14 on 2026-07-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="dept",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
